function numberImages = extractNumbers(im, imagePoints, numberSize)
    
    % Copyright 2018 The MathWorks, Inc.
    
    % Generate rectified puzzle
    fullWidth = 9*numberSize;
    worldPoints = [0, 0; ...
                    fullWidth, 0; ...
                    fullWidth, fullWidth; ...
                    0, fullWidth; ...
                    ];
    outputImage = sudoku.undistort(im, imagePoints, worldPoints);

    % Convert to individual number images
    numberImages = mat2cell(outputImage, ...
                        repmat(numberSize, 1, 9), ...
                        repmat(numberSize, 1, 9), ...
                        3);
end
    